### ISSUE TITLE
FindContour seems to not find contour

### ISSUE THREAD

**Issue by CeadeS** [TrekDev/Xamarin.Android.OpenCV#1]
First I tried to use the function FindContour in my Project and wondered why it does not find any Contour. 
Then I looked in the example "Color Blob Detection". FindContour is used in ColorBlobDetector.cs at Line 91 I guess, The result is printed to the Log in ColorBlobDetecionActivity.cs  at Line 165. It is always zero. So i think, it has something to do with the FindContour funtion. I do not have any exceptions with that. Can you replicate this result?

**Comment by jeremy-ellis-tech** [comment]
Hi CeadeS, I think I'm having the same problem. I may have mistranslated it from the SDK demo provided with the OpenCV SDK. I can't investigate it now as I don't have access to a machine with Xamarin on it today. You can [download the original SDK demo in Java here](https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.1.0/OpenCV-3.1.0-android-sdk.zip/download) and see where I may have gone wrong.

If I haven't translated it wrong it may be a problem with the bindings. If you find anything in the logs that may suggest where it is going wrong please post it back here. I'll have a look myself when I have the chance.

**Comment by CeadeS** [comment]
I am not familiar with bindings but i have a first hint.
If i make a new List from the handle
 `IntPtr native_p1 = global::Android.Runtime.JavaList< global::OpenCV.Core.MatOfPoint>.ToLocalJniHandle(p1);,` 
the Elements seem to be inside the List.
it seems that the IntPtr native_p1 `IntPtr native_p1 = global::Android.Runtime.JavaList< global::OpenCV.Core.MatOfPoint>.ToLocalJniHandle(p1);`
does not point to p1.

```
p1.Add(new MatOfPoint());
p1.Add(new MatOfPoint());
p1.Add(new MatOfPoint());
p1.Count.ToString(); // = 3
IntPtr native_p1 = global::Android.Runtime.JavaList< global::OpenCV.Core.MatOfPoint>.ToLocalJniHandle(p1);
...
...
...
p1.Count.ToString();//=3
JavaList<Core.MatOfPoint>.FromJniHandle(native_p1, JniHandleOwnership.TransferLocalRef).Count.ToString() // = 6
```

**Comment by CeadeS** [comment]
I know it is a bad solution. But without deeper undestanding of what happens, this must work for me. I inserted the Line:
`p1 = JavaList<Core.MatOfPoint>.FromJniHandle(native_p1, JniHandleOwnership.TransferLocalRef);`
So that p1 finaly becomes the output of the findContours Method.

```
public static unsafe void FindContours (global::OpenCV.Core.Mat p0,ref global::System.Collections.Generic.IList<global::OpenCV.Core.MatOfPoint> p1, global::OpenCV.Core.Mat p2, int p3, int p4)
        {
            if (id_findContours_Lorg_opencv_core_Mat_Ljava_util_List_Lorg_opencv_core_Mat_II == IntPtr.Zero)
                id_findContours_Lorg_opencv_core_Mat_Ljava_util_List_Lorg_opencv_core_Mat_II = JNIEnv.GetStaticMethodID (class_ref, "findContours", "(Lorg/opencv/core/Mat;Ljava/util/List;Lorg/opencv/core/Mat;II)V");
            IntPtr native_p1 = global::Android.Runtime.JavaList<global::OpenCV.Core.MatOfPoint>.ToLocalJniHandle (p1);
            try {
                JValue* __args = stackalloc JValue [5];
                __args [0] = new JValue (p0);
                __args [1] = new JValue (native_p1);
                __args [2] = new JValue (p2);
                __args [3] = new JValue (p3);
                __args [4] = new JValue (p4);
                JNIEnv.CallStaticVoidMethod  (class_ref, id_findContours_Lorg_opencv_core_Mat_Ljava_util_List_Lorg_opencv_core_Mat_II,__args);
                p1 = JavaList<Core.MatOfPoint>.FromJniHandle(native_p1, JniHandleOwnership.TransferLocalRef);
            } finally {             
                JNIEnv.DeleteLocalRef (native_p1);
            }
        }
```

**Comment by jeremy-ellis-tech** [comment]
@CeadeS thanks for figuring out a solution. I'll look into the bindings a bit more to see why this is needed.

**Comment by jeremy-ellis-tech** [comment]
@CeadeS Many thanks for spotting this. Turns out the bindings were having a problem with the contours parameter. ~~The bindings don't realise it's a `ref` param and don't set it before exiting `FindContours`. Should be fixed [in this commit](https://github.com/TrekDev/Xamarin.Android.OpenCV/commit/6e614968b3716a3a04df7351a146490c5982f88b).~~ WRONG! See below

**Comment by maurosanjo** [comment]
Hello,

It seems the problem still persists. I'm working no API 23, and deploying and debugging on a Nexus 5.

When the line 36:
`JNIEnv.DeleteLocalRef(native_p1);`

runs, the app crashes with the following output:
`JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0x100005`
[XamarinOpenCVContours.txt](https://github.com/TrekDev/Xamarin.Android.OpenCV/files/221443/XamarinOpenCVContours.txt)

When I comment the line, the contours List is always empty.

Debugging step by step I can see data in contours (count) is populated, but after returning of the function call on ColorBlobDetector.cs, it is empty again.

Still trying to find the glitch... Any ideas? :)

**Comment by jeremy-ellis-tech** [comment]
@maurosanjo thanks the info.

~~I think I need to let the binding generation know that contours is a `ref` parameter somehow. Not sure exactly how, the specific syntax for that if difficult to find.~~ Edit: Nope! See below for fix.

I'll have a look this weekend.

**Comment by jeremy-ellis-tech** [comment]
@maurosanjo, @CeadeS: Fixed in 3d81d8a0b25; tested on a Nexus 5X, Android v 6.0.1.

The method type says it only requires an `IList<MatOfPoint>`, but really it needs a managed `JavaList<MatOfPoint>`. Similar SDK methods are using a managed `JavaList` but by using a utility method that turns a single `Java.Lang.Object` into a `JavaList` holding a single value, so a bit tricky to spot why it wasn't happy with the type.
